# Generated by Django 6.0.3 on 2026-04-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
